# Generated by Django 4.1.7 on 2023-02-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_movie_synopsis"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="added_by",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
