# Generated by Django 4.1.7 on 2023-02-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_movieorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieorder",
            name="buyed_by",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
