# Generated by Django 4.1.7 on 2023-02-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0007_movieorder_buyed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieorder",
            name="title",
            field=models.CharField(max_length=127, null=True),
        ),
    ]
